### ISSUE TITLE
References on jss template show a ? Sign

### ISSUE THREAD

**Issue by derek-corcoran-barrios** [rstudio/rticles#63]
Hello:

I have problems adding References to the jss template. I have use the elsevier template with no problem. I also tried changin the @reference to \cite{references} or \citep{references} but a ? Sign appears where the references should be. I feel I am not pointing to the .bib file in the right way. Any idea of what I am doing wrong?

**Comment by yihui** [comment]
How about this?

```yaml
output:
  rticles::jss_article:
    citation_package: natbib
bibliography: your-references.bib
```

**Comment by derek-corcoran-barrios** [comment]
Hello yihui:

Sorry for the delayed reply, but I wanted to try different versions of what you sent me. It still has the question mark where the references are. The file I am trying to get to work is here https://github.com/derek-corcoran-barrios/DiversityOccupancyJSS/tree/master/DiversityOccuPaper/Untitled

The Rmd is called DiversityOcc.Rmd , and the .bib is called Derek.bib.

Here is my sessioninfo:

R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.2

**Comment by yihui** [comment]
You need to `library(rmarkdown); library(rticles)` before printing `sessionInfo()`. And when in doubt, try to upgrade (R, R packages. and so on).

**Comment by derek-corcoran-barrios** [comment]
Thanks again:

I loaded rmarkdown and rticles, and I know I have the latest version.

Here is the session info:

R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmarkdown_0.9.5 rticles_0.1    

loaded via a namespace (and not attached):
[1] htmltools_0.3.5 tools_3.2.2     Rcpp_0.12.3     digest_0.6.9

**Comment by yihui** [comment]
Should be fixed now (note you need `biblio-style: jss` in the YAML metadata). Thanks!

**Comment by derek-corcoran-barrios** [comment]
Sorry to keep bothering you, should I re-install rtricles from your github now? from what I understand you fixed it in github right?

**Comment by yihui** [comment]
Yes you can install from Github.

**Comment by derek-corcoran-barrios** [comment]
I did, still getting the ? sign, did I change the format ok?

preamble: >
  \usepackage{amsmath}
biblio-style: jss
output:
  rticles::jss_article:
    citation_package: natbib
bibliography: Derek.bib

**Comment by yihui** [comment]
Weird. It works for me;

![screen shot 2016-03-28 at 5 38 37 pm](https://cloud.githubusercontent.com/assets/163582/14092367/f1510084-f50b-11e5-8764-5c2e413b0c11.png)

```
> library(rticles)
> devtools::session_info()
Session info --------------------------------------------------------------------------------------------------------------------
 setting  value                                      
 version  R version 3.2.4 Revised (2016-03-16 r70336)
 system   x86_64, darwin15.3.0                       
 ui       RStudio (0.99.1117)                        
 language (EN)                                       
 collate  en_US.UTF-8                                
 tz       America/Chicago                            
 date     2016-03-28                                 

Packages ------------------------------------------------------------------------------------------------------------------------
 package   * version date       source                            
 curl        0.9.6   2016-02-17 CRAN (R 3.2.3)                    
 devtools    1.10.0  2016-01-23 CRAN (R 3.2.3)                    
 digest      0.6.9   2016-01-08 CRAN (R 3.2.3)                    
 git2r       0.14.0  2016-03-13 CRAN (R 3.2.4)                    
 htmltools   0.3.5   2016-03-25 Github (rstudio/htmltools@60e0bec)
 httr        1.1.0   2016-01-28 CRAN (R 3.2.3)                    
 knitr       1.12.22 2016-03-28 Github (yihui/knitr@c308522)      
 memoise     1.0.0   2016-01-29 CRAN (R 3.2.3)                    
 R6          2.1.2   2016-01-26 CRAN (R 3.2.3)                    
 Rcpp        0.12.4  2016-03-26 CRAN (R 3.2.4)                    
 rmarkdown   0.9.5.3 2016-03-26 Github (rstudio/rmarkdown@4acf3d1)
 rticles   * 0.2     2016-03-28 Github (rstudio/rticles@4bc9f25)  
 withr       1.0.1   2016-02-04 CRAN (R 3.2.3)                    
 yaml        2.1.13  2014-06-12 CRAN (R 3.2.1)                    
```

**Comment by derek-corcoran-barrios** [comment]
mmm, I am guessing that it could be either different OS, I have Ubuntu, or maybe it is that I need to update R (I have 3.2.3)

**Comment by yihui** [comment]
Can you provide a copy of DiversityOcc.tex?

**Comment by derek-corcoran-barrios** [comment]
There is one in the github I sent you, do you need me to send it in another way?

Thanks for being so patient Yihui!

**Comment by derek-corcoran-barrios** [comment]
Hello again:

I just tried it in the computer I have in my job and it worked very well, this one is a windows 7 pc, I will mess around in my ubuntu and tell you how it goes.

Thanks for your patience
